version: '3'

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www
    ports:
      - 8001:80
    links:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www:cached
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]

  worker:
    build:
      context: ./.docker
      dockerfile: Dockerfile-php-worker
    volumes:
      - ./:/var/www:cached
    ports: []
    links:
      - rabbitmq
