FROM php:fpm-stretch
RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        gcc \
        make \
        autoconf \
        libc-dev \
        pkg-config \
        libssl-dev \
        librabbitmq-dev \
        wget \
    && docker-php-ext-install \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql

RUN pecl install amqp
RUN docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY ./ /var/www
WORKDIR /var/www/
