FROM php:7.4-cli
RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        gcc \
        make \
        autoconf \
        libc-dev \
        pkg-config \
        libssl-dev \
        librabbitmq-dev \
        wget \
    && docker-php-ext-install \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql

RUN pecl install amqp

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

RUN wget https://get.symfony.com/cli/installer -O - | bash

RUN  mv /root/.symfony/bin/symfony /usr/local/bin/symfony

COPY ./ /var/www
WORKDIR /var/www/

CMD [ "symfony run -d", "symfony console messenger:consume async" ]
